name: solr
version: 0.1
summary: Starts up solr as forking daemon
description: |
  Solr server as forking daemon Poc

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  solr:
    command: solr-server start
    stop-command: solr-server stop
    daemon: forking
    restart-condition: always
    plugs: [network, network-bind, system-observe]

  configure-nextant:
    command: configure-nextant

parts:
  solr:
    plugin: dump
    source: http://apache.rediris.es/lucene/solr/6.4.0/solr-6.4.0.tgz
    stage-packages: 
      - default-jre-headless
    prime:
      - -*.txt
      - -example
      - -docs
      - -bin/solr
      - -bin/solr.in.sh

  solr-customizations:
    plugin: dump
    source: scripts
    organize:
      'custom-solr': bin/solr
      'solr-server': bin/solr-server
      'solr.in.sh' : bin/solr.in.sh