name: solr
version: 0.1
summary: Starts up solr as forking daemon
description: |
  Solr server as forking daemon. Additionally exposes app to configure Solr 
  for nextant use from nextcloud to perform searches
grade: stable
confinement: strict

apps:
  solr:
    command: solr-server start
    stop-command: solr-server stop
    daemon: forking
    restart-condition: always
    plugs: [network, network-bind, system-observe]

  configure-nextant:
    command: configure-nextant
    plugs: [network, network-bind, system-observe]

hooks:
  configure:
    plugs: [network, network-bind, system-observe]

parts:
  solr:
    plugin: dump
    source: http://apache.rediris.es/lucene/solr/6.4.0/solr-6.4.0.tgz
    stage-packages: 
      - default-jre-headless
    prime:
      - -*.txt
      - -example
      - -docs
      - -bin/solr*
      - -bin/install_solr_service.sh
      - -bin/init.d

  solr-customizations:
    plugin: dump
    source: scripts
    organize:
      '*': bin/
      'custom-solr': bin/solr